# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
avatar:           http://www.drctu.com/Dr._Charmaine_L._Tu-Chiropractic_Physician/FAQs_files/char%20-6251.jpg
title:            'Dr. Charmaine Tu'
tagline:          'Chiropractic Physician'
description:      'Chiropractor'
url:              http://www.drctu.com
baseurl:          /

author:
  name:           'Dr. Charmaine L. Tu'
  url:            https://www.drctu.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/secobarbital/drctu
