# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Dr. Charmaine L. Tu'
tagline:          'Chiropractor'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.drctu.com
baseurl:          /drctu/

author:
  name:           'Dr. Charmaine L. Tu'
  url:            https://www.drctu.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/secobarbital/drctu
